[WIP]feat(qiankun): support to pass history ref from slave to master
umijs/plugins pull request #370
Opened 2020-09-17 11:53 UTC by PeachScript

## 简介

支持父应用通过 `historyRef` 来获取子应用的 history 实例，进而在外层控制子应用路由切换

2020-09-18 03:43 UTC, kuitos requested changes

2020-09-18 03:43 UTC, kuitos commented on packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
> +          props.historyRef.current = history;
用 onHistoryRef 方法的方式吧？history 对象传回来，由组件自己来 set
直接去组件外 set ref.current 有点反模式

2020-09-18 03:43 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroAppWithMemoHistory.tsx.tpl
> +  const history = useRef();
rename 成 historyRef ？不然容易跟 props.history 混淆

2020-09-18 06:34 UTC, PeachScript commented on packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
> +          props.historyRef.current = history;
既然是 ref 感觉还是和 React 原生的 ref 行为保持一致比较好？

2020-09-18 08:52 UTC, kuitos requested changes

2020-09-18 08:52 UTC, kuitos commented on packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
> +          props.historyRef.current = history;
从 react 的视角看的话，函数组件上是不能直接用 ref 的，除非 MicroApp 组件配合 forwardRef 来改造一下。

而且考虑一种混搭的场景，主应用是 vue，子应用是 umi 这种，用 react ref 这种数据结构可能会造成困扰，更普适的应该是 callback method 方案

2020-09-18 11:22 UTC, kuitos requested changes

2020-09-18 11:22 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroAppWithMemoHistory.tsx.tpl
> +      onHistoryInit={h => setHistory(h)}
有两个问题
1. setHistory 调用会触发一次 MicroAppWithMemoHistory 的 rerender，这个应该是不必要的
2. 每次 url 触发 MicroAppWithMemoHistory rerender 时，这里 onHistoryInit 都会生成一个新的引用，从而导致 MicroApp 组件 rerender，这个也可以避免

2020-09-18 11:38 UTC, kuitos approved these changes

2020-09-18 11:38 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroAppWithMemoHistory.tsx.tpl
> +  const historyOpts = useRef({
```suggestion
  // url 的变更不会透传给下游，组件内自己会处理掉，所以这里直接用 ref 来存
  const historyOpts = useRef({
```

2020-09-18 11:47 UTC, kuitos requested changes

2020-09-18 11:47 UTC, kuitos commented on packages/plugin-qiankun/src/slave/lifecycles.ts.tpl
> +          onHistoryInit(history);
```suggestion
          props.onHistoryInit(history);
```

2020-09-21 03:16 UTC, kuitos approved these changes

2020-09-21 03:17 UTC, kuitos requested changes

2020-09-21 03:17 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
> +  onHistoryInit?: History => void;
```suggestion
  onHistoryInit?: (history: History) => void;
```

2020-09-21 03:34 UTC, merged