feat: insert route
umijs/plugins pull request #698
Opened 2021-08-31 17:01 UTC by ttys026

feat: insert route

2021-09-01 07:08 UTC, kuitos reviewed
路由插入场景还需要做一下前置检查，必须符合这个条件，即 route 自身的 path 必须是 target 对应的 path 的子路由，不然直接 throw error，如
```js
// 这里的 target path 必须是 /user 或者 /，如果是 /abc 这种直接抛异常，因为 /user/test 无法成为 /abc 的子路由
{ path: '/user/test', microApp: 'abc', target: '/user' }
```

2021-09-01 07:08 UTC, kuitos commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +      microAppRuntimeRoutes.reverse().forEach((microAppRoute) => {
直接这里过滤一下含 target 配置的 routes？这样的话就是分两块处理，一块是原逻辑，一块是专门给带 target 配置的路由插到指定位置。可以单独提一个 insertMicroAppRouteWithTarget 方法

2021-09-01 08:47 UTC, kuitos commented on packages/plugin-qiankun/src/master/modifyRoutes.ts
> +        routes: injectedRoutes = [],
放到 common.ts 里，然后 template 里 import？跟之前的模式一样

2021-09-01 12:20 UTC, kuitos requested changes

2021-09-01 12:20 UTC, kuitos commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +function patchMicroAppRouteComponent({ routes }) {
如果入参只有一个，就不用对象包一下了，这样调用方代码会更清晰一些

2021-09-01 12:20 UTC, kuitos commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +    microAppRuntimeRoutes.reverse().forEach(microAppRoute => {
insert 处理也应该放这一块，也是只需要处理 microAppRuntimeRoutes 就好了，而不需要扫所有的 routes

2021-09-01 12:20 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +function logError(error: Error) {
线上也异常吧？不然用户线上配错了，发完后都看不出来

2021-09-01 12:20 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +  const traverse = (routes: IRouteProps[]) => {
这里的逻辑可以简化一下，因为我们的场景只支持运行时配置的一级 route 里声明 insert target，可以直接把它过滤出来：
```js
// 支持
routes: [ { path: '/user/test', insert: '/user', microApp: 'test' } ]

// 不支持
routes: [ { path: '/user/test', routes: [{ path: '/user/test'/abc, insert: '/user', microApp: 'test' }] } ]
```

2021-09-02 02:37 UTC, ttys026 commented on packages/plugin-qiankun/src/common.ts
> +  const traverse = (routes: IRouteProps[]) => {
改成只在 runtimeRoute 的最外层找需要被 insert 的路由了

2021-09-06 09:48 UTC, kuitos approved these changes
LGTM

2021-09-06 09:48 UTC, merged