fix(qiankun): add min-height and default classname
umijs/plugins pull request #758
Opened 2021-12-03 07:38 UTC by chenshuai2144

2021-12-03 08:27 UTC, kuitos requested changes

2021-12-03 08:27 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
> +      <div style={{ position: 'relative', minHeigth: 100 }} className={`${wrapperClassName} qiankun-micro-app`}>
这个 minHeight 感觉会变成一个 breaking change，比如里面的微应用没渲染出来，但是还会有一个 100px 的占位。有那个默认的 class 是不是就够了？

2021-12-03 08:32 UTC, chenshuai2144 commented on packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
> +      <div style={{ position: 'relative', minHeigth: 100 }} className={`${wrapperClassName} qiankun-micro-app`}>
这个东西没颜色的，问题应该不大，或者我直接去改loading？

2021-12-03 08:37 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
> +      <div style={{ position: 'relative', minHeigth: 100 }} className={`${wrapperClassName} qiankun-micro-app`}>
改 loading 可以，没什么风险

2021-12-06 05:52 UTC, chenshuai2144 commented on packages/plugin-qiankun/src/master/index.ts
> +          enableLocale: api.hasPlugins(['@umijs/plugin-locale']),
这样可以减少控制台的 getLocale 输出。

2021-12-06 06:14 UTC, chenshuai2144 commented on packages/plugin-qiankun/src/master/AntdLoader.tsx.tpl
> +        alignItems: "center",
用flex 使其居中

2021-12-07 09:13 UTC, merged

2021-12-07 12:59 UTC, kuitos commented
tpl 里字符串还是 double quote 呢[doge.jpg]

2021-12-07 15:10 UTC, chenshuai2144 commented
改掉了

2021-12-14 07:50 UTC, kuitos commented on packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
> +        className={`${wrapperClassName} qiankun-micro-app`}
wrapperClassName 会变成 undefined

2021-12-14 07:52 UTC, gwuhaolin commented on packages/plugin-qiankun/src/master/AntdLoader.tsx.tpl
> +        maxHeight: "60vh",
loading介绍后，这里需要设置为display none