Feat/support index insert
umijs/plugins pull request #796
Opened 2022-02-07 12:27 UTC by duwonders

支持指定插入位置

2022-02-09 04:08 UTC, kuitos requested changes

2022-02-09 04:08 UTC, kuitos commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +  const insertRoutes = microAppRuntimeRoutes.filter(r => r.insert || r.insertBefore || r.insertAfter);
insertBefore 就够了，insertAfter 跟 insert 是一样的

2022-02-09 07:37 UTC, duwonders commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +  const insertRoutes = microAppRuntimeRoutes.filter(r => r.insert || r.insertBefore || r.insertAfter);
insert是插入到target的子节点、insertAfter是插入target的后面

2022-02-09 12:00 UTC, kuitos requested changes

2022-02-09 12:03 UTC, kuitos requested changes

2022-02-09 12:03 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
>  ): IRouteProps | null => {
这个类型不对了

2022-02-09 12:06 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +  fatherPath: string,
父节点用 parent 更常规一些，parentPath/parentNode/parentRoute

2022-02-10 02:38 UTC, duwonders commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +  const insertRoutes = microAppRuntimeRoutes.filter(r => r.insert || r.insertBefore || r.insertAfter);
了解了，我把insertAfter干掉，不过如果换名字的话感觉会影响线上的

2022-02-10 06:42 UTC, kuitos commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +  const insertRoutes = microAppRuntimeRoutes.filter(r => r.insert || r.insertBefore || r.insertAfter);
insert 还是保留，但是文档里推荐用新的？`appendChildTo: '/parentPath'` 如何？

2022-02-10 09:09 UTC, duwonders commented on packages/plugin-qiankun/src/master/masterRuntimePlugin.ts.tpl
> +  const insertRoutes = microAppRuntimeRoutes.filter(r => r.insert || r.insertBefore || r.insertAfter);
get，我改一下

2022-02-11 07:40 UTC, kuitos reviewed
appendChildTo 为准，insert 是 legacy 配置

2022-02-11 07:40 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +  const mod = (microAppRoute.insert || microAppRoute.appendChildTo)
```suggestion
  const mod = (microAppRoute.appendChildTo || microAppRoute.insert)
```

2022-02-11 07:40 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +  const target = microAppRoute.insert || microAppRoute.insertBefore || microAppRoute.appendChildTo;
```suggestion
  const target = microAppRoute.appendChildTo || microAppRoute.insert || microAppRoute.insertBefore;
```

2022-02-11 07:40 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +  ? 'insert'
```suggestion
  ? 'appendChildTo'
```

2022-02-11 07:40 UTC, kuitos commented on packages/plugin-qiankun/src/common.ts
> +      case 'insert':
```suggestion
      case 'appendChildTo':
```

2022-02-11 07:44 UTC, kuitos approved these changes
LGTM

2022-02-11 07:45 UTC, merged