fix(plugin-qiankun): fixed pnpm installation dependency error
umijs/plugins pull request #869
Opened 2022-06-15 02:55 UTC by wyy0512

修复 使用 pnpm 安装plugin-qiankun，临时文件部分依赖找不到的问题
[#issues](https://github.com/umijs/umi/issues/8148)

2022-06-16 02:56 UTC, PeachScript requested changes

2022-06-16 02:56 UTC, PeachScript commented on packages/plugin-qiankun/src/master/index.ts
> +          qiankunPath: winPath(require.resolve('qiankun')),
`require.resolve` 拿到的可能是 cjs 产物，参考这个逻辑只获取包的文件夹，具体拿什么产物交给 webpack 去处理：https://github.com/umijs/umi-next/blob/353e9679510db9a90185f07d7761d3373c2ebb1d/packages/plugins/src/qiankun/master.ts#L133

2022-06-16 02:56 UTC, PeachScript commented on packages/plugin-qiankun/src/master/index.ts
> +          lodashConcatPath: winPath(require.resolve('lodash/concat')),
只声明 `lodashPath`，子路径还是原样拼接引入？

2022-06-16 02:56 UTC, PeachScript commented on packages/plugin-qiankun/src/master/index.ts
> +          qiankunPath: winPath(require.resolve('qiankun')),
另外 `qiankun` 不能直接改成绝对路径，先判断下 `api.config.externals.qiankun` 是否存在，否则内部燕鸥插件对 `qiankun` 做 external 的逻辑会失效、导致运行时出现多个 `qiankun` 实例，微应用沙箱会出问题

2022-06-16 02:56 UTC, PeachScript commented on packages/plugin-qiankun/src/master/MicroApp.tsx.tpl
> +    const wrapperStyle = { position: "relative" }
这里修改的原因是？

2022-06-16 13:26 UTC, wyy0512 commented on packages/plugin-qiankun/src/master/index.ts
> +          lodashConcatPath: winPath(require.resolve('lodash/concat')),
+1

2022-06-23 07:49 UTC, PeachScript approved these changes
+1

2022-06-23 07:49 UTC, merged